### PR TITLE
Cra

### PR DESCRIPTION
**Pull request by Leative**
added rules and test cases to cra case study. very early experiments with modifiers as HOTs.

### CODE REVIEW

**Comment by szschaler** [comment]
What's the idea with the HOTs?

**Comment by Leative** [comment]
There are two ideas about HOTs:
At first, we just tried to use HOTs to automatically generate selection rules respecting different modifiers. For example, the class selection and random feature selection might both be used in multi-point crossover. However, we probably don't want to copy & paste the whole rule sets just to introduce multi-point crossover versions of them. However, we paused the development of that concept due to the time restrictions.

The second idea is to write a set of framework rules which can generalize the concept of crossover but keep placeholders for (type) information needed to adapt the rules to a specific use case. HOTs might be used to allow that (type) information to be specified as a parameter by the user. The HOT could then be applied to generate a use case specific crossover by replacing the placeholders in the framework rules.

**Comment by szschaler** [comment]
I see. That sounds like it would eventually turn into Stefan's PhD, right?

**Comment by Leative** [comment]
Actually, we wanted to see if we can get a prototype for the second idea working in a timely manner. But yes, going deeper into that topic could be part of my PhD.

**Pull request merged**
